#eureka
eureka:
  instance:
    # Hostname here tells downstream Services (e.g., org-service, unit-service, etc):
    # â€œYou can find me (Eureka Server) at http://local.service-registry.docker:8761.â€
    hostname: local.service-registry.docker  # ğŸ‘ˆ the name this server is known by to others
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      zone: default  # Optional for zone-aware routing
  client:
    register-with-eureka: false  # This server won't register itself
    fetch-registry: false        # This server won't try to pull from others
    service-url:
      # instance.hostname and defaultZone domain name (local.service-registry.docker) must be same
      defaultZone: http://local.service-registry.docker:8761/eureka/
      # Future: add other nodes here for cluster
      # defaultZone: http://eureka1:8761/eureka/,http://eureka2:8761/eureka/
  environment: CV-DEVELOPMENT
  datacenter: CV-DEVELOPMENT-LOCAL
